<a href="https://colab.research.google.com/github/Batoul-aljaddouh/Animal-Image-Dataset/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [26]:
tf.__version__
'2.8.2'

'2.8.2'

In [27]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values 
y = dataset.iloc[:, -1].values

In [28]:
print(X[:1,:])

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]]


In [29]:
print(y)

[1 0 1 ... 1 1 0]


In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [31]:
print(X[:5,:])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]]


In [32]:
print(X[4:5,:])

[[850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]]


In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1],)], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [34]:
print(X[:1,:])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]]


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [37]:
ann = tf.keras.models.Sequential()

In [38]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [39]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [40]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [41]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [42]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5539 - accuracy: 0.7381
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4506 - accuracy: 0.7970
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4328 - accuracy: 0.8083
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8191
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8226
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4173 - accuracy: 0.8241
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4136 - accuracy: 0.8248
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8264
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8285
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3994 - accura

In [43]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (32, 6)                   78        
                                                                 
 dense_4 (Dense)             (32, 6)                   42        
                                                                 
 dense_5 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [44]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

[[False]]


In [45]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [46]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 197  208]]


0.861